/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GoalType = { 'timeBased' : bigint } |
  { 'taskBased' : bigint };
export interface StudySession {
  'startTime' : bigint,
  'duration' : bigint,
  'endTime' : bigint,
  'date' : bigint,
  'subjectId' : string,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'color' : string,
  'creationDate' : bigint,
}
export interface _SERVICE {
  'addSubject' : ActorMethod<[string, string, string], undefined>,
  'editSubject' : ActorMethod<[string, string, string], undefined>,
  'getDailyGoal' : ActorMethod<[], [] | [GoalType]>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjectSessions' : ActorMethod<[string], Array<StudySession>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getWeeklySessions' : ActorMethod<[bigint, bigint], Array<StudySession>>,
  'recordSession' : ActorMethod<[StudySession], undefined>,
  'removeSubject' : ActorMethod<[string], undefined>,
  'setDailyGoal' : ActorMethod<[GoalType], undefined>,
  'setTaskBasedGoal' : ActorMethod<[bigint], undefined>,
  'setTimeBasedGoal' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];