/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GoalType = IDL.Variant({
  'timeBased' : IDL.Nat,
  'taskBased' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'startTime' : IDL.Int,
  'duration' : IDL.Nat,
  'endTime' : IDL.Int,
  'date' : IDL.Int,
  'subjectId' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'creationDate' : IDL.Int,
});

export const idlService = IDL.Service({
  'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'editSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getDailyGoal' : IDL.Func([], [IDL.Opt(GoalType)], ['query']),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSubjectSessions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getWeeklySessions' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'recordSession' : IDL.Func([StudySession], [], []),
  'removeSubject' : IDL.Func([IDL.Text], [], []),
  'setDailyGoal' : IDL.Func([GoalType], [], []),
  'setTaskBasedGoal' : IDL.Func([IDL.Nat], [], []),
  'setTimeBasedGoal' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GoalType = IDL.Variant({
    'timeBased' : IDL.Nat,
    'taskBased' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'startTime' : IDL.Int,
    'duration' : IDL.Nat,
    'endTime' : IDL.Int,
    'date' : IDL.Int,
    'subjectId' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'creationDate' : IDL.Int,
  });
  
  return IDL.Service({
    'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'editSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getDailyGoal' : IDL.Func([], [IDL.Opt(GoalType)], ['query']),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSubjectSessions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getWeeklySessions' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'recordSession' : IDL.Func([StudySession], [], []),
    'removeSubject' : IDL.Func([IDL.Text], [], []),
    'setDailyGoal' : IDL.Func([GoalType], [], []),
    'setTaskBasedGoal' : IDL.Func([IDL.Nat], [], []),
    'setTimeBasedGoal' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };