/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudySession {
    startTime: bigint;
    duration: bigint;
    endTime: bigint;
    date: bigint;
    subjectId: string;
}
export type GoalType = {
    __kind__: "timeBased";
    timeBased: bigint;
} | {
    __kind__: "taskBased";
    taskBased: bigint;
};
export interface Subject {
    id: string;
    name: string;
    color: string;
    creationDate: bigint;
}
export interface backendInterface {
    addSubject(id: string, name: string, color: string): Promise<void>;
    editSubject(id: string, name: string, color: string): Promise<void>;
    getDailyGoal(): Promise<GoalType | null>;
    getStudySessions(): Promise<Array<StudySession>>;
    getSubjectSessions(subjectId: string): Promise<Array<StudySession>>;
    getSubjects(): Promise<Array<Subject>>;
    getWeeklySessions(weekStart: bigint, weekEnd: bigint): Promise<Array<StudySession>>;
    recordSession(session: StudySession): Promise<void>;
    removeSubject(id: string): Promise<void>;
    setDailyGoal(goal: GoalType): Promise<void>;
    setTaskBasedGoal(tasks: bigint): Promise<void>;
    setTimeBasedGoal(hours: bigint): Promise<void>;
}
import type { GoalType as _GoalType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSubject(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1, arg2);
            return result;
        }
    }
    async editSubject(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSubject(arg0, arg1, arg2);
            return result;
        }
    }
    async getDailyGoal(): Promise<GoalType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyGoal();
                return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyGoal();
            return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStudySessions(): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudySessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudySessions();
            return result;
        }
    }
    async getSubjectSessions(arg0: string): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectSessions(arg0);
            return result;
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async getWeeklySessions(arg0: bigint, arg1: bigint): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySessions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySessions(arg0, arg1);
            return result;
        }
    }
    async recordSession(arg0: StudySession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSession(arg0);
            return result;
        }
    }
    async removeSubject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSubject(arg0);
            return result;
        }
    }
    async setDailyGoal(arg0: GoalType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyGoal(to_candid_GoalType_n4(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyGoal(to_candid_GoalType_n4(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async setTaskBasedGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTaskBasedGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTaskBasedGoal(arg0);
            return result;
        }
    }
    async setTimeBasedGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimeBasedGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimeBasedGoal(arg0);
            return result;
        }
    }
}
function from_candid_GoalType_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalType): GoalType {
    return from_candid_variant_n3(uploadFile, downloadFile, value);
}
function from_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoalType]): GoalType | null {
    return value.length === 0 ? null : from_candid_GoalType_n2(uploadFile, downloadFile, value[0]);
}
function from_candid_variant_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeBased: bigint;
} | {
    taskBased: bigint;
}): {
    __kind__: "timeBased";
    timeBased: bigint;
} | {
    __kind__: "taskBased";
    taskBased: bigint;
} {
    return "timeBased" in value ? {
        __kind__: "timeBased",
        timeBased: value.timeBased
    } : "taskBased" in value ? {
        __kind__: "taskBased",
        taskBased: value.taskBased
    } : value;
}
function to_candid_GoalType_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): _GoalType {
    return to_candid_variant_n5(uploadFile, downloadFile, value);
}
function to_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "timeBased";
    timeBased: bigint;
} | {
    __kind__: "taskBased";
    taskBased: bigint;
}): {
    timeBased: bigint;
} | {
    taskBased: bigint;
} {
    return value.__kind__ === "timeBased" ? {
        timeBased: value.timeBased
    } : value.__kind__ === "taskBased" ? {
        taskBased: value.taskBased
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
